name: monitor
run-name: Site monitor
on:
  workflow_dispatch: # Manual
  schedule: # Run the action on a cron schedule
    - cron: '33 0 * * *' # Every day at 12:33 am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Run monitor
      run: |
        python3 scripts/monitor.py ${{ secrets.NTFY_CHANNEL }}